modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="ego_weapons"
version="0.18.15"
displayName="ego_weapons"
credits="Adds a variety of weapons from the project moon franchise."
displayURL=""
authors="M3tte"

[[dependencies.ego_weapons]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.2.39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ego_weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.ego_weapons]]
    modId="epicfight"
    mandatory=true
    versionRange="[16.6.4,)"
    ordering="BEFORE"
    side="BOTH"





